# Application
FPS = 64
DEBUG_INFO_INTERVAL = FPS * 1

# Tiles
TILE_SIZE = 24
MOVABLE_SPEED = 2
MOVABLE_MOVE_SKIP = 0

WALL_SLIDE_FACTOR = 2
WALL_HEALTH = 2

# Game director
MAX_TANKS_AT_ONCE = 4
DEFAULT_TANK_COUNT = 16
NEW_TANK_SPAWN_MAX_COOLDOWN = 160
PLAYER_LIVES = 3
GAME_OVER_COOLDOWN = FPS * 4

# Tanks
PLAYER_SPEED = 2
PLAYER_MOVE_SKIP = 0
PLAYER_HEALTH = 1

TANK_SPEED = 2
TANK_MOVE_SKIP = 3
TANK_HEALTH = 1
TANK_SIZE = TILE_SIZE * 2
TANK_SCALE = 3

TANK_MIN_FIRE_COOLDOWN = 18
TANK_TRACK_ANIM_DURATION = 3

# Particles
PARTICLE_LIFESPAN = FPS * 10
EXPLOSION_SIZE = 48
EXPLOSION_LIFESPAN = 60
BLING_SIZE = 48
BLING_LIFESPAN = 100

BULLET_SPEED = 5
BULLET_LIFESPAN = FPS * 10

# AI
AI_LOGIC_TIME_STEP = 1
AI_VISION_TILE_RANGE = 3
AI_JUNCTION_TURN_CHANCE = .25
AI_SHOOT_PERIOD = 60
AI_FLAG_DIRECTION_BIAS = 2.

# UI
UI_SIDE_PANEL_SIZE = 90
UI_TANK_ICON_SIZE = 21
UI_TANK_ICONS_MAX_ROWS = 15
UI_TANK_ICONS_MAX_COLS = 2
UI_TANK_ICONS_GAP = 5
UI_TANK_ICONS_WIDTH = UI_TANK_ICON_SIZE * UI_TANK_ICONS_MAX_COLS\
                      + (UI_TANK_ICONS_MAX_COLS-1) * UI_TANK_ICONS_GAP
UI_TANK_ICONS_HEIGHT = UI_TANK_ICON_SIZE * UI_TANK_ICONS_MAX_ROWS\
                      + (UI_TANK_ICONS_MAX_ROWS-1) * UI_TANK_ICONS_GAP
UI_TANK_ICONS_TOP_PAD = 20
UI_PLAYER_ICON_SIZE = 32